### ISSUE TITLE
Rename `*.txt` to `*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [ivangayton/overpass_queries#1]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by FloEdelmann** [comment]
@ivangayton Would a PR be accepted?

**Comment by ivangayton** [comment]
Oh, certainly!!

**Comment by ivangayton** [comment]
Apologies for not responding earlier; I haven't been using this code for a while, but if it's useful to you I'd be delighted to accept a pull request.

**Comment by FloEdelmann** [comment]
@ivangayton No problem :)
I created a pull request: #2
